### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by sofiapoh** [Authosaurus/UX#42]
I see that you guys have designed and built everything mobile first, that's cool!

For ease of viewing, you could have a container around everything that has a max width of a phone or tablet so that you don't have to worry about your layout getting ruined when you visit it on desktop.

This really helps clients that are not so tech savvy (like client-sofia) see the layout because so many people that are not developers struggle using devtools.

**Comment by SavageWilliam** [comment]
Fantastic idea, we'll work on this right away. (we've gone for an iphone 6 as optimal sizing, we hope that works well for client-sofia)

**Comment by sofiapoh** [comment]
That's cool!
