### ISSUE TITLE
CVV explanation does not show on mobile

### ISSUE THREAD

**Issue by msachi** [Authosaurus/UX#68]
Tested on iPhone 5, both Chrome and Safari

**Comment by jsms90** [comment]
Does on mine (Samsung)

**Comment by njsfield** [comment]
Solution: this is an IOS Bug, on your body tag, set this rule...

```html
<body class="landing" ontouchstart="">
...
```

[See here](http://www.beacontechnologies.com/blog/2015/05/simple-little-tricks-for-web-transition-touch-events-on-mobile-devices/)
